# Site settings
title: "Sai Maduri"
description: "Sai Maduri's Portfolio Website. CS student at Rutgers University"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sai C. Maduri"
resume_title:                   "CS @ Rutgers University"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "saicmaduri@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(908) 917-3705"
resume_contact_address:         "Princeton, NJ"

resume_header_contact_info:     "Princeton, NJ • saicmaduri@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>My name is Sai, and I&#39;m studying Computer Science at Rutgers University. I&#39;m currently seeking internships for Spring or Summer 2023 in Software Engineering or other related roles. If you think I&#39;d be a good fit for your company, please feel free to reach out to me by email or social media!</p>
<p>Here are some places I&#39;ve put my software engineering skills to use</p>
<ul>
<li><b>Twitch</b>, the Amazon-owned interactive live streaming service, working on product infrastructure in the VOD team</li>
<li><b>Bloomberg</b>, the creators of the world-renowned Bloomberg Terminal, working on both internal tools &amp; product in the Fixed Income Analytics team and working on infrastructure in the Data Retention team</li>
<li><b>Leverton</b>, a startup specializing in AI-powered data extraction and contract analytics, working on product in a data science role</li>
</ul>
<p>I&#39;ve primarily used Java, Python, Go, and JavaScript/TypeScript throughout my internships and am familiar with many tools and technologies. I am also a motivated individual who can quickly learn and apply brand-new concepts (check out more about me from the perspective of my peers, mentors, and managers in the recommendation section of my LinkedIn). Additionally, having managed organizations and events of 100+ people, I can step into a leadership role in a team-oriented environment when necessary.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/saimaduri"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/saimaduri"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "https://github.com/saimaduri/resume/raw/main/SaiMaduriResume.pdf"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
